### ISSUE TITLE
"Connection write error" when starting work

### ISSUE THREAD

**Issue by fosterseth** [ansible/receptor#83] opened 2020-08-07 19:36 UTC
```
ERROR 2020/08/07 15:29:27 Connection write error: write unix /tmp/foo.sock->@: use of closed network connection
ERROR 2020/08/07 15:29:27 Not all bytes written
```

This log message shows up on the control node when submitting work `start` or `submit` command

However, job seems to run fine despite the error message.

foo.yml
```
---
- node:
    id: foo
    allowedpeers: bar,fish

- control-service:
    service: control
    filename: /tmp/foo.sock

- tcp-listener:
    port: 2222

- work-command:
    service: 100cat
    command: bash
    params: "-c \"seq 100 | /home/sfoster/sockceptor/sleepcat.sh\""
```

first I removed `/tmp/receptor` and `/tmp/foo.sock` then ran the following,
`./receptor -c foo.yml`
`nc -U /tmp/foo.sock` > `work start 100cat`

error will show up in the log at this point

I am synced with `devel`

**Comment by ghjm** [comment] 2020-08-07 20:06
I haven't seen this happen.  Can you give more complete details on how to reproduce it?  Like maybe post your config files?

**Comment by fosterseth** [comment] 2020-08-07 20:14
@ghjm I updated with the config file

**Comment by fosterseth** [comment] 2020-08-07 20:18
@ghjm nevermind, issue seems to be fixed with this PR you have open

https://github.com/project-receptor/receptor/pull/82

**Comment by ghjm** [comment] 2020-08-07 20:20
Ah ok thanks, forgot I still needed to merge that.  Receptorctl was also broken because of this. I just merged it.

**Closed as completed** 2020-08-07 20:21 UTC
