### ISSUE TITLE
Error: 'NoneType' object has no attribute 'readline' when running receptorctl

### ISSUE THREAD

**Issue by adamruzicka** [ansible/receptor#186] opened 2020-09-24 12:48 UTC
receptor docker image: 3d295df248ed

Receptor config:
```yaml
---
- log-level:
    level: debug
- node:
    id: r1
    allowedpeers: r2
- tcp-listener:
    port: 9999
```

Steps to reproduce:
1) Run receptor node with the given config
2) Exec into the container
3) Run `receptorctl --socket tcp://localhost:9999 status`

Actual results:
```sh
# receptorctl --socket tcp://localhost:9999 status
TCP socket, host localhost port 9999
Error: 'NoneType' object has no attribute 'readline'
```

Expected results:
The status, probably

**Comment by ghjm** [comment] 2020-09-24 12:57
I have reproduced this - receptorctl over a TCP socket gives this error and fails to connect.

Note that `tcp-listener` listens for Receptor-protocol node-to-node connections.  Receptorctl, on the other hand, expects to talk to the control service protocol (which more commonly runs over a Unix domain socket).  So the configuration as given above would not be expected to work, even after we fix the bug in receptorctl.  Here is the configuration I used to reproduce the issue:

```
---
- log-level:
    level: debug
- node:
    id: r1
    allowedpeers: r2
- control-service:
    service: control
- tcp-server:
    port: 9999
    remotenode: localhost
    remoteservice: control
- tcp-listener:
    port: 1234
```

With this configuration, I can `nc localhost 9999` and talk to the control service, but I still get the error when trying to talk to it with receptorctl.

**Comment by ghjm** [comment] 2020-10-05 23:47
Should be fixed by https://github.com/project-receptor/receptor/pull/199.

**Comment by squidboylan** [comment] 2020-10-06 22:58
We currently don't have testing for receptorctl and that seems to be the level this would have to be tested at, I'll make an issue for adding receptorctl testing and close this

**Closed as completed by squidboylan** 2020-10-06 22:58 UTC
