### ISSUE TITLE
No error message when using wrong certificate

### ISSUE THREAD

**Issue by thenets** [ansible/receptor#421] opened 2021-09-16 15:02 UTC
## Why

During the startup, if the user adds one invalid certificate for the Receptor mesh, the main Receptor process will die without a proper error message.

## Summary

Forcing the use of an invalid certificate makes the Receptor crash without any output message.

## Step to reproduce

1. Create two empty instances
2. Install Receptor with TLS
3. Create any invalid certificate
4. Overwrite the certificate

Certicate replaced:
- `/etc/receptor/tls/${TLS_CERT_NAME}.key`
- `/etc/receptor/tls/${TLS_CERT_NAME}.crt`

## Expected result

- Fail
- Some messages saying the certificate is invalid or the nodes are using different certificates when trying to talk to each other.

## Actual result

- Fail
- No error message

**Comment by fosterseth** [comment] 2021-11-09 19:54
TLS configuration is loaded in during receptor bootup, and that information resides in memory. Each time we grab a new connection to a remote node, we use the in-memory TLS information. This means replacing any of the certs/keys on the filesystem will have zero effect on the running receptor process. Only if receptor is restarted would these new certs/keys be used.

**Comment by thenets** [comment] 2021-11-11 19:08
@fosterseth yeap. The problem is more related to the installation process. If the user adds an invalid certificate during the installation process, the process will die without a proper error message and this will be harder to troubleshoot.

The check will be more useful maybe in the next release if we allow the user to renovate the mesh certificate.

**Comment by sarabrajsingh** [comment] 2021-11-18 06:10
@shanemcd @fosterseth @eqrx - we got a couple of failing unit tests here that I want to address before merging anything. i tagged @eqrx because he's the author of the unit tests.

the receptor binary will now error out very early on when it gets invoked by the units tests (if bad certs are given). <b> This behavior was a request from QE.</b>The following unit tests will fail due to the binary producing the following errors:

note, the double fails is because a `tcp-listener` receptor node and a `ws-listener` node throw expections in each unit test.

### TestTCPSSLClientAuthFailBadKey
##### expected to fail because we are passing bad keys to receptor
```bash
[sarsingh@fedora receptor]$ /opt/go/bin/go test -timeout 30s -run ^TestTCPSSLClientAuthFailBadKey$ github.com/ansible/receptor/tests/functional/mesh
--- FAIL: TestTCPSSLClientAuthFailBadKey (0.00s)
    --- FAIL: TestTCPSSLClientAuthFailBadKey/tcp-listener (0.80s)
        tls_test.go:306: failed to create mesh: node /tmp/receptor-testing/TestTCPSSLClientAuthFailBadKey/tcp-listener/mesh-503771442/node1-457088820 exited early
    --- FAIL: TestTCPSSLClientAuthFailBadKey/ws-listener (1.07s)
        tls_test.go:306: failed to create mesh: node /tmp/receptor-testing/TestTCPSSLClientAuthFailBadKey/ws-listener/mesh-543834536/node1-081799399 exited early
FAIL
FAIL	github.com/ansible/receptor/tests/functional/mesh	1.081s
FAIL
[sarsingh@fedora receptor]$
```
##### caused by (receptor output)
```bash
[sarsingh@fedora receptor]$ cat "/tmp/receptor-testing/TestTCPSSLClientAuthFailBadKey/tcp-listener/mesh-999622342/node1-666481517/stdout"
Error: x509: certificate signed by unknown authority
[sarsingh@fedora receptor]$ 
```

### TestTCPSSLClientAuthFailNoKey
##### expected to fail we are testing no keys
```bash
[sarsingh@fedora receptor-cl]$ /opt/go/bin/go test -timeout 30s -run ^TestTCPSSLServerAuthFailBadKey$ github.com/ansible/receptor/tests/functional/mesh
--- FAIL: TestTCPSSLServerAuthFailBadKey (0.00s)
    --- FAIL: TestTCPSSLServerAuthFailBadKey/ws-listener (0.84s)
        tls_test.go:466: failed to create mesh: node /tmp/receptor-testing/TestTCPSSLServerAuthFailBadKey/ws-listener/mesh-672919237/node2-221661503 exited early
    --- FAIL: TestTCPSSLServerAuthFailBadKey/tcp-listener (1.11s)
        tls_test.go:466: failed to create mesh: node /tmp/receptor-testing/TestTCPSSLServerAuthFailBadKey/tcp-listener/mesh-170688739/node2-986200845 exited early
FAIL
FAIL	github.com/ansible/receptor/tests/functional/mesh	1.119s
FAIL
[sarsingh@fedora receptor-cl]$ 
```

#### caused by (receptor output)
```bash
[sarsingh@fedora receptor-cl]$ cat "/tmp/receptor-testing/TestTCPSSLClientAuthFailNoKey/ws-listener/mesh-462781410/node2-633247076/stdout"
Error: client cert and key must both be supplied
[sarsingh@fedora receptor-cl]$ 
```

### TestTCPSSLConnections
##### unknown reason. is this supossed to fail?
```bash
[sarsingh@fedora receptor-cl]$ /opt/go/bin/go test -timeout 30s -run ^TestTCPSSLConnections$ github.com/ansible/receptor/tests/functional/mesh
--- FAIL: TestTCPSSLConnections (0.00s)
    --- FAIL: TestTCPSSLConnections/ws-listener (0.42s)
        tls_test.go:117: failed to create mesh: node /tmp/receptor-testing/TestTCPSSLConnections/ws-listener/mesh-505669790/node3-909659871 exited early
    --- FAIL: TestTCPSSLConnections/tcp-listener (0.66s)
        tls_test.go:117: failed to create mesh: node /tmp/receptor-testing/TestTCPSSLConnections/tcp-listener/mesh-929211011/node3-608629165 exited early
FAIL
FAIL	github.com/ansible/receptor/tests/functional/mesh	0.674s
FAIL
[sarsingh@fedora receptor-cl]$ 
```
#### caused by (receptor output)
```bash
[sarsingh@fedora receptor]$ cat "/tmp/receptor-testing/TestTCPSSLConnections/tcp-listener/mesh-603555057/node3-146259758/stdout"
Error: client cert and key must both be supplied
[sarsingh@fedora receptor]$ 
```

### TestTCPSSLServerAuthFailBadKey
##### bad certs given (expected to fail)
```bash
[sarsingh@fedora receptor-cl]$ /opt/go/bin/go test -timeout 30s -run ^TestTCPSSLServerAuthFailBadKey$ github.com/ansible/receptor/tests/functional/mesh
--- FAIL: TestTCPSSLServerAuthFailBadKey (0.00s)
    --- FAIL: TestTCPSSLServerAuthFailBadKey/tcp-listener (0.91s)
        tls_test.go:466: failed to create mesh: node /tmp/receptor-testing/TestTCPSSLServerAuthFailBadKey/tcp-listener/mesh-323360484/node2-738542518 exited early
    --- FAIL: TestTCPSSLServerAuthFailBadKey/ws-listener (1.21s)
        tls_test.go:466: failed to create mesh: node /tmp/receptor-testing/TestTCPSSLServerAuthFailBadKey/ws-listener/mesh-583905751/node2-396204577 exited early
FAIL
FAIL	github.com/ansible/receptor/tests/functional/mesh	1.218s
FAIL
[sarsingh@fedora receptor-cl]$
```
#### caused by (from receptor)
```bash
[sarsingh@fedora receptor-cl]$ cat "/tmp/receptor-testing/TestTCPSSLClientAuthFailBadKey/tcp-listener/mesh-779053415/node1-028130202/stdout"
Error: x509: certificate signed by unknown authority
```
### TestTCPSSLServerAuthFailNoKey
##### this test is throwing the wrong error
```bash
[sarsingh@fedora receptor-cl]$ /opt/go/bin/go test -timeout 30s -run ^TestTCPSSLServerAuthFailNoKey$ github.com/ansible/receptor/tests/functional/mesh
--- FAIL: TestTCPSSLServerAuthFailNoKey (0.00s)
    --- FAIL: TestTCPSSLServerAuthFailNoKey/tcp-listener (0.64s)
        tls_test.go:379: failed to create mesh: node /tmp/receptor-testing/TestTCPSSLServerAuthFailNoKey/tcp-listener/mesh-477966640/node2-340750818 exited early
    --- FAIL: TestTCPSSLServerAuthFailNoKey/ws-listener (0.80s)
        tls_test.go:379: failed to create mesh: node /tmp/receptor-testing/TestTCPSSLServerAuthFailNoKey/ws-listener/mesh-216704371/node2-815735325 exited early
FAIL
FAIL	github.com/ansible/receptor/tests/functional/mesh	0.809s
FAIL
[sarsingh@fedora receptor-cl]$ 
```
#### caused by (receptor output)
```bash
[sarsingh@fedora receptor-cl]$ cat "/tmp/receptor-testing/TestTCPSSLServerAuthFailNoKey/ws-listener/mesh-356439610/node2-524273532/stdout"
Error: x509: certificate signed by unknown authority
[sarsingh@fedora receptor-cl]$ 
```

so now, the question becomes, do we refactor these tests? or don't introduce my changes into `devel`?

**Comment by sarabrajsingh** [comment] 2022-08-23 18:38
@thenets i think we can close this GH issue. Let me know.

**Closed as completed** 2022-11-15 06:36 UTC
Labels: type:enhancement
